export const identifiers = {
  BEST_BEFORE: 'bestBefore',
  CODE: 'code',
  DESCRIPTION: 'description',
  EDIBLE: 'edible',
  EMAIL: 'email',
  FIRST_NAME: 'firstName',
  HAS_ACCESS: 'hasAccess',
  ID: 'id',
  LAST_NAME: 'lastName',
  PASSWORD: 'password',
  PRICE: 'price',
  ROLE: 'role',
  TYPE: 'type',
  VALUE: 'value',
  WEIGHT: 'weight',
};
