export const identifiers = {
  ACTIVE: 'active',
  CODE: 'code',
  CREATED_AT: 'createdAt',
  DEPRECATED: 'deprecated',
  DESCRIPTION: 'description',
  EMAIL: 'email',
  FIRST_NAME: 'firstName',
  HAS_ACCESS: 'hasAccess',
  ID: 'id',
  LAST_NAME: 'lastName',
  NAME: 'name',
  PASSWORD: 'password',
  REPEAT_PASSWORD: 'repeatPassword',
  ROLE: 'role.name',
  TYPE: 'type',
  UNDEPRECATED: 'undeprecated',
  UPDATED_AT: 'updatedAt',
  USER_HAS_TO_SET_PASSWORD: 'userHasToSetPassword',
  VALUE: 'value',
};
