export default {
  SET_USERNAME         : 'SET_USERNAME',
  LOGIN_USER           : 'LOGIN_USER',
  LOGIN_USER_REQUEST   : 'LOGIN_USER_REQUEST',
  LOGIN_USER_REJECTED  : 'LOGIN_USER_REJECTED',
  LOGIN_USER_FULFILLED : 'LOGIN_USER_FULFILLED',
  LOGOUT_USER          : 'LOGOUT_USER',
  FORGOT_PASSWORD      : 'FORGOT_PASSWORD',
};
