export default {
  GET_USERS: 'GET_USERS',
  GET_USERS_PENDING: 'GET_USERS_PENDING',
  GET_USERS_REJECTED: 'GET_USERS_REJECTED',
  GET_USERS_FULFILLED: 'GET_USERS_FULFILLED',
  GET_USERS_BY_ID: 'GET_USERS_BY_ID',
  GET_USERS_BY_ID_PENDING: 'GET_USERS_BY_ID_PENDING',
  GET_USERS_BY_ID_REJECTED: 'GET_USERS_BY_ID_REJECTED',
  GET_USERS_BY_ID_FULFILLED: 'GET_USERS_BY_ID_FULFILLED',
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_PENDING: 'CREATE_USER_PENDING',
  CREATE_USER_REJECTED: 'CREATE_USER_REJECTED',
  CREATE_USER_FULFILLED: 'CREATE_USER_FULFILLED',

};
